import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import HeaderNavBar from "@/components/HeaderNavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kitespots</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className={styles.main}>
            <HeaderNavBar />
            <div className={"h-96 w-96 bg-amber-400 page-body"}></div>
        </div>
    </>
  )
}
